### ISSUE TITLE
xapi result.success and result.completion properties not supported

### ISSUE THREAD

**Issue by garemoko** [h5p/h5p-php-library#2]
H5P's tracking does not support the result.success and result.completion properties, which are important properties used by most quiz authoring tools and LRSs that report on quiz data (e.g. Watershed). 

It looks like these could easily be added in as additional optional properties to [setScoredResult](https://github.com/h5p/h5p-php-library/blob/cb8640195ebd8b0f8c3903ae6a831a7bc66966a1/js/h5p-x-api-event.js#L22-L39). 

Would I be right in assuming that if this library is updated that this would also be reflected in the next release of the WordPress plugin? 

Would it be helpful for me to make a PR?

**Comment by falcon-git** [comment]
A PR for these would be great!

In QuestionSet result.success would make a lot of sense since it is possible to configure how many percent of the points you must obtain in order to pass the set. For a standalone Multichoice however this isn't configurable, so I don't know if it should be added to statements from anything but the Question Set. What do you think?

For result.completion we might need to pass a property to setScoredResult so that it knows if the user completed or not?

**Comment by garemoko** [comment]
For a stand alone multi choice, success would be true if you got the question right. 

I *think* we'll need to pass parameters to setScoredResult for both completion and success. Perhaps completion should default to true if not passed though. Success should default to null. I'll aim to do a PR for this today.

**Comment by falcon-git** [comment]
Ok, great!

**Comment by falcon-git** [comment]
(Do note that both result.completion and result.success is optional here https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#result)

**Comment by garemoko** [comment]
They are optional, but it's good practice to include optional properties where the data exists. The reason they are optional is not because they aren't important, but because xAPI can be used to track things other than quiz questions which may not have this data.

**Comment by falcon-git** [comment]
Ok, I see that you didn't put anything into success by default, and both are overridable. I will talk to the sponsor of the xAPI features in H5P about adding these changes so that we don't surprise them
