### ISSUE TITLE
Old, vulnerable jquery version included

### ISSUE THREAD

**Issue by tmuras** [h5p/h5p-php-library#54]
jquery library included is at v1.9.1 version:
https://github.com/h5p/h5p-php-library/blob/master/js/jquery.js

and it has a know vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2015-9251

**Comment by H5P-Helper** [comment]
Were there no patch or something we could use to just fix the
security problem?

Kind regards,

Svein-Tore (Falcon)

h5p/h5p-php-library on October 31, 2018 at 12:20pm wrote:

jquery library included is at v1.9.1 version:

https://github.com/h5p/h5p-php-library/blob/master/js/jquery.js

and it has a know vulnerability:
https://nvd.nist.gov/vuln/detail/CVE-2015-9251

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
( https://github.com/h5p/h5p-php-library/issues/54 ), or mute the
thread

**Comment by falcon-git** [comment]
It is patched. Thank you for reporting.
