### ISSUE TITLE
Incompatibility with Canvas messages.js

### ISSUE THREAD

**Issue by benroot** [h5p/h5p-php-library#73]
## Summary
Console errors every time H5P object embedded into Canvas LMS. (caused by iframe resize messages)

## Description
H5P embedded iframes send messages to the window.parent and these messages cause console errors with Canvas LMS'  own resizing system in the file messages.js. Canvas attempts to parse the data object from the H5P message as a JSON string causing an exception. 

I have not located when this incompatibility was introduced.

<img width="303" alt="image" src="https://user-images.githubusercontent.com/34732/70459157-6e705d00-1a68-11ea-9380-1bdaf7ee15b1.png">

## Steps to Reproduce
Copy the embed code from any h5p.org (or self-hosted) H5P activity. Paste the embed code into Canvas LMS. Open up the developer console and see the error from messages.js.

**Comment by icc** [comment]
H5P uses the browser's postMessage API to communicate across frames which is essential for allowing the parent frame to resize the content's iframe when the content changes its height.
We cannot change this without breaking existing content.

The error is printed because Canvas assumes that all postMessage event data is a JSON string that needs decoding. This can be fixed by simply checking if the event data is, in fact, a string before trying to parse it: [lti/messages.js#L62](https://github.com/instructure/canvas-lms/blob/e1a65570c302c1dff50a060d270aa6f00eaab911/public/javascripts/lti/messages.js#L62)
i.e. `typeof e.data === 'string'`

**Comment by benroot** [comment]
Thanks for your response. I have created an issue in the Canvas repository.
